version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
                
    - name: stg_sales_orders
      columns:
          - name: sales_order_number
            tests:
                - not_null
                - unique

    - name: stg_sales_order_items
      columns:
          - name: sales_order_number
            tests:
                - not_null
          - name: item_number
            tests:
                - not_null

    - name: stg_purchase_orders
      columns:
          - name: purchase_order_number
            tests:
               - not_null
               - unique
          - name: vendor_number
            tests:
                - not_null

    - name: stg_purchase_order_items
      description: Purchase OrderItems Enriched With Header and Vendor Details
      columns:
          - name: purchase_order_number
            tests:
                - not_null

          - name: item_number
            tests:
                - not_null

          - name: vendor_number
            tests:
               - not_null

          - name: vendor_number
          
          - name: material_number

              
                         
    
              
               
              
              
               
                
                